# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='infor',
            field=models.IntegerField(default=0),
        ),
    ]
