# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='description',
        ),
    ]
