# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
