# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20190522_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='pictur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insta.Image'),
            preserve_default=False,
        ),
    ]
