# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20190522_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='pictur',
        ),
        migrations.AddField(
            model_name='comments',
            name='picture',
            field=models.IntegerField(default=0),
        ),
    ]
